// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PlanVibe.Infrastructure.Persistencia;

#nullable disable

namespace PlanVibe.Infrastructure.Persistencia.Migraciones
{
    [DbContext(typeof(PlanVibeDbContext))]
    [Migration("20260811130537_MigracionInicial")]
    partial class MigracionInicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("app")
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("roles", "identidad");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("roles_reclamaciones", "identidad");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("cuentas_reclamaciones", "identidad");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("cuentas_accesos_externos", "identidad");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("cuentas_roles", "identidad");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("cuentas_tokens", "identidad");
                });

            modelBuilder.Entity("PlanVibe.Domain.Categorias.Categoria", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Activa")
                        .HasColumnType("boolean")
                        .HasColumnName("activa");

                    b.Property<string>("Clave")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("clave");

                    b.Property<string>("ColorHex")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasColumnName("color_hex");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("nombre");

                    b.Property<int>("Orden")
                        .HasColumnType("integer")
                        .HasColumnName("orden");

                    b.Property<uint>("VersionFila")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("Clave")
                        .IsUnique()
                        .HasDatabaseName("ix_categorias_clave");

                    b.ToTable("categorias", "app");
                });

            modelBuilder.Entity("PlanVibe.Domain.Quedadas.Quedada", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("ActualizadaEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("actualizada_en");

                    b.Property<Guid>("CategoriaId")
                        .HasColumnType("uuid")
                        .HasColumnName("categoria_id");

                    b.Property<DateTimeOffset>("CreadaEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creada_en");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("descripcion");

                    b.Property<int>("Estado")
                        .HasColumnType("integer")
                        .HasColumnName("estado");

                    b.Property<string>("MotivoDeCancelacion")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("motivo_de_cancelacion");

                    b.Property<string[]>("Normas")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("normas");

                    b.Property<Guid>("OrganizadorId")
                        .HasColumnType("uuid")
                        .HasColumnName("organizador_id");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("titulo");

                    b.Property<long>("UltimoOrdenDeLlegada")
                        .HasColumnType("bigint")
                        .HasColumnName("ultimo_orden_de_llegada");

                    b.Property<uint>("VersionFila")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<Point>("ubicacion")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("geography(Point,4326)")
                        .HasColumnName("ubicacion")
                        .HasComputedColumnSql("ST_SetSRID(ST_MakePoint(longitud, latitud), 4326)::geography", true);

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Capacidad", "PlanVibe.Domain.Quedadas.Quedada.Capacidad#Capacidad", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<int>("Maximo")
                                .HasColumnType("integer")
                                .HasColumnName("capacidad");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Cuando", "PlanVibe.Domain.Quedadas.Quedada.Cuando#FranjaTemporal", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<TimeSpan>("Duracion")
                                .HasColumnType("interval")
                                .HasColumnName("duracion");

                            b1.Property<DateTimeOffset>("Inicio")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("inicio");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Donde", "PlanVibe.Domain.Quedadas.Quedada.Donde#PuntoEncuentro", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("DireccionExacta")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("direccion_exacta");

                            b1.Property<bool>("EsLugarPublico")
                                .HasColumnType("boolean")
                                .HasColumnName("es_lugar_publico");

                            b1.Property<double>("Latitud")
                                .HasColumnType("double precision")
                                .HasColumnName("latitud");

                            b1.Property<double>("Longitud")
                                .HasColumnType("double precision")
                                .HasColumnName("longitud");

                            b1.Property<string>("Lugar")
                                .IsRequired()
                                .HasMaxLength(120)
                                .HasColumnType("character varying(120)")
                                .HasColumnName("lugar");

                            b1.Property<string>("Referencia")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("referencia");
                        });

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId")
                        .HasDatabaseName("ix_quedadas_categoria");

                    b.HasIndex("Estado")
                        .HasDatabaseName("ix_quedadas_estado");

                    b.HasIndex("OrganizadorId")
                        .HasDatabaseName("ix_quedadas_organizador");

                    b.HasIndex("ubicacion")
                        .HasDatabaseName("ix_quedadas_ubicacion");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("ubicacion"), "gist");

                    b.ToTable("quedadas", "app");
                });

            modelBuilder.Entity("PlanVibe.Domain.Usuarios.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("ActualizadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("actualizado_en");

                    b.Property<int>("AnioDeNacimiento")
                        .HasColumnType("integer")
                        .HasColumnName("anio_de_nacimiento");

                    b.Property<string>("Biografia")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("biografia");

                    b.Property<string>("Ciudad")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("ciudad");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("correo");

                    b.Property<DateTimeOffset>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en");

                    b.Property<int>("Estado")
                        .HasColumnType("integer")
                        .HasColumnName("estado");

                    b.Property<string>("NombreVisible")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("nombre_visible");

                    b.Property<DateTimeOffset>("NormasAceptadasEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("normas_aceptadas_en");

                    b.Property<uint>("VersionFila")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<string>("VersionNormasAceptada")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("version_normas_aceptada");

                    b.PrimitiveCollection<List<string>>("_intereses")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("intereses");

                    b.Property<int[]>("_roles")
                        .IsRequired()
                        .HasColumnType("integer[]")
                        .HasColumnName("roles");

                    b.HasKey("Id");

                    b.HasIndex("Correo")
                        .IsUnique()
                        .HasDatabaseName("ix_usuarios_correo");

                    b.ToTable("usuarios", "app");
                });

            modelBuilder.Entity("PlanVibe.Infrastructure.Identidad.CuentaDeAcceso", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreadaEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("cuentas_de_acceso", "identidad");
                });

            modelBuilder.Entity("PlanVibe.Infrastructure.Identidad.TokenDeRenovacion", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en");

                    b.Property<string>("Dispositivo")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("dispositivo");

                    b.Property<DateTimeOffset>("ExpiraEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expira_en");

                    b.Property<Guid>("Familia")
                        .HasColumnType("uuid")
                        .HasColumnName("familia");

                    b.Property<string>("HashDelToken")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("hash_del_token");

                    b.Property<DateTimeOffset?>("RevocadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revocado_en");

                    b.Property<DateTimeOffset?>("UsadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("usado_en");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id");

                    b.HasIndex("ExpiraEn")
                        .HasDatabaseName("ix_tokens_expiracion");

                    b.HasIndex("Familia")
                        .HasDatabaseName("ix_tokens_familia");

                    b.HasIndex("HashDelToken")
                        .IsUnique()
                        .HasDatabaseName("ix_tokens_hash");

                    b.ToTable("tokens_de_renovacion", "identidad");
                });

            modelBuilder.Entity("PlanVibe.Infrastructure.Persistencia.EntradaDeAuditoria", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("accion");

                    b.Property<Guid?>("ActorId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_id");

                    b.Property<string>("Metadatos")
                        .HasColumnType("jsonb")
                        .HasColumnName("metadatos");

                    b.Property<string>("ObjetoId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("objeto_id");

                    b.Property<DateTimeOffset>("OcurridoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ocurrido_en");

                    b.Property<string>("TipoDeObjeto")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("tipo_de_objeto");

                    b.HasKey("Id");

                    b.HasIndex("ActorId", "OcurridoEn")
                        .HasDatabaseName("ix_auditoria_actor_fecha");

                    b.HasIndex("TipoDeObjeto", "ObjetoId")
                        .HasDatabaseName("ix_auditoria_objeto");

                    b.ToTable("entradas", "auditoria");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("PlanVibe.Infrastructure.Identidad.CuentaDeAcceso", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("PlanVibe.Infrastructure.Identidad.CuentaDeAcceso", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PlanVibe.Infrastructure.Identidad.CuentaDeAcceso", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("PlanVibe.Infrastructure.Identidad.CuentaDeAcceso", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PlanVibe.Domain.Quedadas.Quedada", b =>
                {
                    b.OwnsMany("PlanVibe.Domain.Quedadas.Asistencia", "Asistencias", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<DateTimeOffset>("ActualizadaEn")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("actualizada_en");

                            b1.Property<int>("Estado")
                                .HasColumnType("integer")
                                .HasColumnName("estado");

                            b1.Property<long>("OrdenDeLlegada")
                                .HasColumnType("bigint")
                                .HasColumnName("orden_de_llegada");

                            b1.Property<DateTimeOffset>("SolicitadaEn")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("solicitada_en");

                            b1.Property<Guid>("UsuarioId")
                                .HasColumnType("uuid")
                                .HasColumnName("usuario_id");

                            b1.Property<Guid>("quedada_id")
                                .HasColumnType("uuid")
                                .HasColumnName("quedada_id");

                            b1.HasKey("Id");

                            b1.HasIndex("UsuarioId")
                                .HasDatabaseName("ix_asistencias_usuario");

                            b1.HasIndex("quedada_id", "UsuarioId")
                                .IsUnique()
                                .HasDatabaseName("ix_asistencias_quedada_usuario");

                            b1.ToTable("asistencias", "app");

                            b1.WithOwner()
                                .HasForeignKey("quedada_id");
                        });

                    b.Navigation("Asistencias");
                });

            modelBuilder.Entity("PlanVibe.Domain.Usuarios.Usuario", b =>
                {
                    b.OwnsOne("PlanVibe.Domain.Usuarios.ObjetosDeValor.DatosDeVerificacion", "Verificacion", b1 =>
                        {
                            b1.Property<Guid>("UsuarioId")
                                .HasColumnType("uuid");

                            b1.Property<DateTimeOffset?>("ActualizadaEn")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("verificacion_actualizada_en");

                            b1.Property<int>("Estado")
                                .HasColumnType("integer")
                                .HasColumnName("verificacion_estado");

                            b1.Property<bool>("MayoriaDeEdadConfirmada")
                                .HasColumnType("boolean")
                                .HasColumnName("verificacion_mayoria_de_edad");

                            b1.Property<string>("Observacion")
                                .HasMaxLength(300)
                                .HasColumnType("character varying(300)")
                                .HasColumnName("verificacion_observacion");

                            b1.Property<string>("Proveedor")
                                .HasMaxLength(60)
                                .HasColumnType("character varying(60)")
                                .HasColumnName("verificacion_proveedor");

                            b1.Property<string>("ReferenciaExterna")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("verificacion_referencia");

                            b1.HasKey("UsuarioId");

                            b1.ToTable("usuarios", "app");

                            b1.WithOwner()
                                .HasForeignKey("UsuarioId");
                        });

                    b.Navigation("Verificacion")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
